In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('C:\\Users\\rabis\\Desktop\\deep\\Churn_Modelling.csv')

In [3]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
X=data.iloc[:,3:13].values
y=data.iloc[:,13].values

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])

In [8]:
labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])

In [9]:
onehotencoder=OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray()
X= X[:, 1:]

In [10]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.25, random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
import keras
from keras.models import Sequentialquential
from keras.layers import Dense

In [15]:
model=Sequential()

In [16]:
model.add(Dense(6, activation='relu', input_dim=11))
model.add(Dense(6, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [22]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [23]:
model.fit(X_train, y_train,batch_size=10, epochs=100)

Epoch 1/100
7500/7500 [==============================] - 2s 303us/step - loss: 0.5076 - acc: 0.7819
Epoch 2/100
7500/7500 [==============================] - 1s 160us/step - loss: 0.4445 - acc: 0.7963
Epoch 3/100
7500/7500 [==============================] - 1s 144us/step - loss: 0.4357 - acc: 0.7963
Epoch 4/100
7500/7500 [==============================] - 1s 144us/step - loss: 0.4317 - acc: 0.7997
Epoch 5/100
7500/7500 [==============================] - 1s 151us/step - loss: 0.4287 - acc: 0.8068
Epoch 6/100
7500/7500 [==============================] - 1s 148us/step - loss: 0.4258 - acc: 0.8141
Epoch 7/100
7500/7500 [==============================] - 1s 146us/step - loss: 0.4223 - acc: 0.8184
Epoch 8/100
7500/7500 [==============================] - 1s 151us/step - loss: 0.4185 - acc: 0.8228
Epoch 9/100
7500/7500 [==============================] - 1s 149us/step - loss: 0.4150 - acc: 0.8248
Epoch 10/100
7500/7500 [==============================] - 1s 147us/step - loss: 0.4117 - acc: 0.8301

7500/7500 [==============================] - 1s 194us/step - loss: 0.3302 - acc: 0.8631
Epoch 83/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3303 - acc: 0.8617
Epoch 84/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3307 - acc: 0.8655
Epoch 85/100
7500/7500 [==============================] - 1s 158us/step - loss: 0.3304 - acc: 0.8655 1s - loss
Epoch 86/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3298 - acc: 0.8640
Epoch 87/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3295 - acc: 0.8652
Epoch 88/100
7500/7500 [==============================] - 1s 157us/step - loss: 0.3297 - acc: 0.8643
Epoch 89/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3299 - acc: 0.8631
Epoch 90/100
7500/7500 [==============================] - 1s 158us/step - loss: 0.3299 - acc: 0.8644
Epoch 91/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3276 - acc: 

In [24]:
y_pred=model.predict(X_test)

In [27]:
y_pred=(y_pred>0.5)

In [28]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [31]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)

In [32]:
cm

array([[1881,  110],
       [ 240,  269]], dtype=int64)